import type { Starship } from '@/lib/auth/types';

export const MOCK_STARSHIPS: Starship[] = [
  // Death Squadron
  {
    title: 'The Devastator',
    modelId: 3,
    location: 3,
    roles: [],
    fleet: 'Death Squadron',
  },
  {
    title: 'The Avenger',
    modelId: 3,
    location: 3,
    roles: [],
    fleet: 'Death Squadron',
  },
  {
    title: "Vader's Shuttle",
    modelId: 22,
    location: 4,
    roles: [],
    fleet: 'Death Squadron',
  },
  {
    title: "Vader's TIE Advanced x1",
    modelId: 13,
    location: 4,
    roles: [],
    fleet: 'Death Squadron',
  },
  {
    title: 'The Executor',
    modelId: 15,
    location: 5,
    roles: [],
    fleet: 'Death Squadron',
  },
  // Imperial Remnant Fleet
  {
    title: "Gideon's Light Cruiser",
    modelId: 23,
    location: 7,
    roles: [],
    fleet: 'Imperial Remnant Fleet',
  },
  {
    title: 'Escort Frigate 1',
    modelId: 23,
    location: 7,
    roles: ['escort_commander'],
    fleet: 'Imperial Remnant Fleet',
  },
  {
    title: 'Escort Frigate 2',
    modelId: 23,
    location: 7,
    roles: ['escort_commander'],
    fleet: 'Imperial Remnant Fleet',
  },
  {
    title: 'Escort Frigate 3',
    modelId: 23,
    location: 7,
    roles: ['escort_commander'],
    fleet: 'Imperial Remnant Fleet',
  },
  {
    title: 'TIE Fighter 1',
    modelId: 13,
    location: 8,
    roles: ['logistics_officer'],
    fleet: 'Imperial Remnant Fleet',
  },
  {
    title: 'TIE Fighter 2',
    modelId: 13,
    location: 8,
    roles: ['logistics_officer'],
    fleet: 'Imperial Remnant Fleet',
  },
  // Starfighter Assault Fleet
  {
    title: 'X-Wing 1',
    modelId: 12,
    location: 1,
    roles: [],
    fleet: 'Starfighter Assault Fleet',
  },
  {
    title: 'X-Wing 2',
    modelId: 12,
    location: 1,
    roles: [],
    fleet: 'Starfighter Assault Fleet',
  },
  {
    title: 'Bomber 1',
    modelId: 11,
    location: 1,
    roles: [],
    fleet: 'Starfighter Assault Fleet',
  },
  {
    title: 'Bomber 2',
    modelId: 11,
    location: 1,
    roles: [],
    fleet: 'Starfighter Assault Fleet',
  },
  // Heavy Alliance Line Fleet
  {
    title: 'Mon Calamari Cruiser 1',
    modelId: 27,
    location: 2,
    roles: [],
    fleet: 'Heavy Alliance Line Fleet',
  },
  {
    title: 'Escort Frigate 1',
    modelId: 23,
    location: 2,
    roles: ['escort_commander'],
    fleet: 'Heavy Alliance Line Fleet',
  },
  {
    title: 'Escort Frigate 2',
    modelId: 23,
    location: 2,
    roles: ['escort_commander'],
    fleet: 'Heavy Alliance Line Fleet',
  },
  {
    title: 'A-Wing 1',
    modelId: 28,
    location: 2,
    roles: [],
    fleet: 'Heavy Alliance Line Fleet',
  },
  {
    title: 'A-Wing 2',
    modelId: 28,
    location: 2,
    roles: [],
    fleet: 'Heavy Alliance Line Fleet',
  },
  {
    title: 'B-Wing',
    modelId: 29,
    location: 2,
    roles: [],
    fleet: 'Heavy Alliance Line Fleet',
  },
];
